---
name: Deploy transformations

on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy transformations
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Extract branch name
              shell: bash
              # If branch name has hyphens, replace with underscores
              run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/} | sed -e s/-/_/g)"
              id: extract_name

            - name: Resolve secrets
              shell: bash
              env:
                  BRANCH: ${{ steps.extract_name.outputs.name }}
              run: echo "##[set-output name=jetfire_api_key;]$(echo JETFIRE_API_KEY_${BRANCH})"
              id: extract_secrets

            - name: Deploy transformations
              uses: cognitedata/jetfire-cli@v2
              with:
                  path: transformations
                  api-key: ${{ secrets[steps.extract_secrets.outputs.jetfire_api_key] }}
                  # If you are not using the main cluster (europe-west1-1), specify it here:
                  # cluster: greenfield
              env:
                  # List all needed keys referenced by your manifests:
                  MY_TRANSFORMATION_API_KEY: ${{ secrets.MY_TRANSFORMATION_API_KEY }}
